copy  /y .\SEMITouch\Packet\ChipWrapper.h           ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\
copy  /y .\SEMITouch\Packet\ChipWrapper.cpp         ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\
copy  /y .\SEMITouch\Packet\RefSelf.h               ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\
copy  /y .\Include\Macro.h                          ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\Include\
copy  /y .\Include\NativeTestInterface.h            ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\Include\
copy  /y .\Include\automaticInterface.h            ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\Include\
copy  /y .\Include\SEMITouch.h                      ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\Include\
copy  /y .\Util\Header\helper.h                     ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\Util\
copy  /y .\Util\Realize\helper.cpp                  ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\Util\
copy  /y .\Util\Header\framework.h                  ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\Util\
copy  /y .\Util\Header\Wait.h                       ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\Util\
copy  /y .\Util\Header\tinyxml.h                    ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\Util\
copy  /y .\Util\Realize\tinyxml.cpp                 ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\Util\
copy  /y .\Util\Header\checksum.h                       ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\Include\

xcopy /y .\SEMITouch\Packet\Chip\*                  ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\Chip
xcopy /y .\SEMITouch\Packet\Protocal\*              ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\Protocal
xcopy /y .\SEMITest\TestSrc\*                       ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\TestSrc
xcopy /y .\SEMITest\Config\*                        ..\..\Phone\android\SemiTouchDevelop\invokebridge\src\main\cpp\Config